all:
	javac -cp ".:protobuf/edu/illinois/cs/salmon/fredshoppinglist/protobuf-java-2.6.1.jar:protobuf/edu/illinois/cs/salmon/fredshoppinglist/archistar-smc-0.2-wip.jar" PAMRAC.java PTLS.java protobuf/edu/illinois/cs/salmon/fredshoppinglist/PAMRACProto.java ServerDownload.java Scrypt.java PBKDF.java ConsoleInterface.java
